# GitHub Repository Configuration
name: GSTelegramDiscord
description: "🚀 Автоматическая интеграция Google Sheets с Telegram и Discord ботами. Синхронизация данных, уведомления и автоматизация рабочих процессов."
website: "https://github.com/IZenApp/GSTelegramDiscord"

# Topics/Tags for GitHub
topics:
  - telegram-bot
  - googlesheets
  - discord-webhook
  - automation
  - google-sheets-api
  - telegram-api
  - discord-api
  - data-sync
  - nodejs
  - bot-framework
  - webhook-integration
  - spreadsheet-automation

# Features
features:
  - "🔧 Модульная архитектура"
  - "🧪 Виртуальное тестирование"
  - "📚 Полная документация"
  - "⚙️ Автоматизированные скрипты"
  - "🛡️ Безопасный демо-режим"
  - "📦 Готов к продакшену"

# Language and framework
language: JavaScript
runtime: Node.js
license: MIT
